### ISSUE TITLE
Library with ES3/ES5 code

### ISSUE THREAD

**Issue by snadifhbklasdvffkal** [edulan/react-virtual-kanban#23]
Library without using require.js or any module Loader. library like jquery

**Comment by edulan** [comment]
Hi @snadifhbklasdvffkal, sorry but I don't get your point with loaders, can you elaborate a bit more please?

**Comment by snadifhbklasdvffkal** [comment]
At the moment i work with asp.net mvc with nuget package Manger with Typescript and React. So adding this through npm is not possible for me.
